site_name: Kubernetes Gateway API Inference Extension
repo_url: https://github.com/kubernetes-sigs/gateway-api-inference-extension
repo_name: kubernetes-sigs/gateway-api-inference-extension
site_dir: site
docs_dir: site-src
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  logo: images/logo/logo-text-large-horizontal-white.png
  favicon: images/k8s-favicon.png
  features:
    - search.highlight
    - navigation.tabs
    - navigation.top
    - navigation.expand
  palette:
    primary: custom
  custom_dir: site-src/overrides
edit_uri: edit/main/site-src/
plugins:
  - search
  - awesome-pages
  - macros:
      j2_line_comment_prefix: "#$"
  - mermaid2
  - spellcheck:
      backends:
      - symspellpy
      - codespell:
          dictionaries: [clear, rare, en-GB_to_en-US]
      # known_words can also be a list of words
      known_words: known_words.txt
      # ignore words in <code> tags
      ignore_code: yes
      # minimum length of words to consider
      min_length: 2
      # maximum number of capital letters in a word
      max_capital: 1
      # keep unicode characters
      allow_unicode: no
      # skip all directories except site-src
      skip_files:
      - api/*
      - client-go/*
      - cmd/*
      - config/*
      - docs/*
      - hack/*
      - internal/*
      - pkg/*
      - test/*
      - tools/*
      # whether to only check in strict mode
      strict_only: no
markdown_extensions:
  - admonition
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - toc:
      permalink: true
  - tables
nav:
  - Overview:
    - Introduction: index.md
    - Concepts:
      - API Overview: concepts/api-overview.md
      - Conformance: concepts/conformance.md
      - Roles and Personas: concepts/roles-and-personas.md
    - Implementations: implementations.md
    - FAQ: faq.md
  - Guides:
    - User Guides:
      - Getting started: guides/index.md
      - Adapter Rollout: guides/adapter-rollout.md
    - Implementer's Guide: guides/implementers.md
  - Reference:
    - API Reference: reference/spec.md
    - API Types:
      - InferencePool: api-types/inferencepool.md
      - InferenceModel: api-types/inferencemodel.md
  - Enhancements:
    - Overview: gieps/overview.md
  - Contributing:
    - How to Get Involved: contributing/index.md
    - Developer Guide: contributing/devguide.md
    - Docs Guide: contributing/docs.md