# netlify configuration
[build]
publish = "."
command = ""
# available here https://github.com/netlify/build-image/blob/focal/included_software.md#languages
environment.PYTHON_VERSION = "3.8"

# Specify that we want to build from the docs branch
[context.production]
  branch = "docs"